### ISSUE TITLE
why not fork https://github.com/352Media/skilltree directly?

### ISSUE THREAD

**Issue by kimmking** [phodal/skilock#3]
why not fork https://github.com/352Media/skilltree directly?

**Comment by phodal** [comment]
1. 先创建了这个repo，然后才发现了https://github.com/352Media/skilltree
2. 想着这不是自己要的最后效果，就想着先基于skilltree，再继续。
3. 接着发现skilltree里面的代码写得不符合我的胃口，接着就想着重构、测试等等。。

直接fork有什么特殊的规则?

**Comment by kimmking** [comment]
直接fork再改，是大家默认的潜规则。

无所谓啊，赞一个，good work。
：） toi那个项目更赞。

**Comment by phodal** [comment]
直接fork不好改的说，如果有以后就先fork~~
