### ISSUE TITLE
feature: 增加分享时的截图

### ISSUE THREAD

**Issue by kimmking** [phodal/skilock#4]
增加分享时的截图

**Comment by phodal** [comment]
这个当前做，感觉性价比不高

**Comment by kimmking** [comment]
这个感觉加上phantomjs，几句代码就搞定了。

**Comment by phodal** [comment]
@kimmking 问题是这个是分享时候才出现的截图，而分享的时候图片都会被压缩。

**Comment by kimmking** [comment]
用户输入完成的时候，生成一个图，丢到免费的qiniu或aliyun即可。

**Comment by phodal** [comment]
@kimmking 实现我觉得不是问题，问题是成本太高，而且感觉价值不高。。

现在是纯前端，托管在github上，可以push，就更新代码。如果要生成截图的话，就需要独立部署等等。
