### ISSUE TITLE
关于技能的一些小建议

### ISSUE THREAD

**Issue by lindsayee** [phodal/skilock#6]
前端初心者 > _ < // 不是很懂，按照自己的经验提几个小建议…

有一些技能感觉分级太少了，比如JS（目前只有1）、HTML（图标用了5不过点满技能点感觉也和5没什么关系）…

有一些技能可能不需要前置技能点，比如平面设计工具之类的…

有一些技能点需要增加/拆分，比如调试和分析、移动端、安全、开发管理、运维、测试等…

还有几个技能的设计感觉有点奇怪，比如：
- 精通Web设计：定义只是可以把设计转换为HTML&CSS而已_(:з」∠)_
- jQuery效果的第一个操作是熟练操作DOM模型，却要在精通Web设计之后才能开启（虽然按照这个“精通”的定义是没问题…）
- AJAX & APIs，没有分级，需要精通前端开发 & 精通后端开发才能开启，实际可能不需要到精通阶段……

**Comment by xh4n3** [comment]
继续补充：
不懂储存过程也可以写NOSQL啊，NOSQL放在底下有点不科学。
总体来说很赞啊。

**Comment by phodal** [comment]
@lindsayee 好提议。最近在外地。看看app/data/web.json 看看怎么添加？

**Comment by phodal** [comment]
@xh4n3 新建一个level会比较好?

**Comment by kimmking** [comment]
这个问题，我建议你找几个前端大牛一起来讨论。
@atian25 @xufei @fouber @RubyLouvre @damoqiongqiu @JacksonTian

**Comment by atian25** [comment]
点了下，觉得覆盖面不够，而且前置技能啥的也怪怪的。

**Comment by phodal** [comment]
@atian25 举个例子

**Comment by kinogam** [comment]
单元测试漏掉是个致命的缺陷

**Comment by phodal** [comment]
@kinogam 这个会在新的Tech Web里面覆盖[https://github.com/phodal/sherlock](https://github.com/phodal/sherlock)。

**Comment by RubyLouvre** [comment]
安全是一个，性能是 一个， 测试还分许多种

**Comment by phodal** [comment]
@RubyLouvre 嗯。在下一个版本会考虑全面的。:smile: :smile:  TDD、重构什么的一堆堆。

**Comment by phodal** [comment]
Hi, all, 这些技能小建议将会在这里实现: https://github.com/phodal/sherlock， 需要加什么技能试试可以在这里添加 https://github.com/phodal/awesome-developer?  :smiley:
